src/objects/Product__c.object
<CustomObject>
    <description>Main PLM Object</description>
    <fields>
        <fullName>Costing_ERP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Costing__ERP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InActive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Project</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>InActive</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Projects and Approval</label>
    <nameField>
        <displayFormat>PRJ-{0000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects and Approval</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CostingDomain.cls
/*Description : This class is used as a Domain class for Projects VF page, costing VF component. Purpose of this class is to perforn CRUD Operations.
Projects data
Created By : Mustafa
Created Date : November 2016*/
public class CostingDomain {

    /*Description : Purpose of this method is to save the project */
     public static boolean saveCostingProduct(Product__c productRecord,boolean erpData){
		boolean isSuccess = true;
        List<Product__c> productLst = new List<Product__c>();
        productRecord.Costing_ERP__c = erpData;
        productLst.add(productRecord);
        Database.UpsertResult[] results = Database.upsert(productLst,true);
    	for(Integer i=0;i<results.size();i++){
    		if(!results[i].isSuccess()){
    			isSuccess = false;	
    		}	
    	}
    	return isSuccess;
    }
        
    /*Description : Purpose of this method is to save the project */
    public static boolean saveCostingProject(Project__c projectRecord){
        boolean isSuccess = true;
        projectRecord.Status__c='Completed';
        Database.UpsertResult results = Database.upsert(projectRecord);
      	return isSuccess;      
    }
}