src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Not Submitted</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
                <color>#E27001</color>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
                <color>#A845DC</color>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
                <color>#F3D904</color>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <picklist>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R&amp;D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC Opt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regulatory Clearance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA/QC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SHE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MFG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warehouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costing</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Projects and Approval</label>
    <nameField>
        <displayFormat>PRJ-{0000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects and Approval</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QA_QC_SpecificationDomain.cls
/*Description : This class is used as a Domain class QA_QC_Specification component.
Projects data
Created By : Mustafa
Created Date : November 2016*/
public class QA_QC_SpecificationDomain {
    
    //Description:- Purpose of this method is to Insert/Update PM_QA_Spec__c records.
    public static boolean upsertQaQcSpecification(List<PM_QA_Spec__c> lstQaQcSpecfication){
    	boolean isSuccess = true;
        if(lstQaQcSpecfication.size()>0){
            List<Database.UpsertResult> results = Database.upsert(lstQaQcSpecfication, true);
            for(Database.UpsertResult varResult : results){
                if(!varResult.isSuccess()){
                    isSuccess = false;
                }
            }
        }    
        return isSuccess;
    }
    
    //Description:- Purpose of this method is to delete PM_QA_Spec__c records.
    public static boolean deleteQaQcSpecification(List<PM_QA_Spec__c> lstQaQcSpecficationToDelete){
    	boolean isSuccess = true;
        if(lstQaQcSpecficationToDelete.size()>0){
            List<Database.DeleteResult> results = Database.delete(lstQaQcSpecficationToDelete,true);
            for(Database.DeleteResult varResult : results){
                if(!varResult.isSuccess()){
                    isSuccess = false;
                }
            }
        }
        return isSuccess;
    }
    
    /*Description : Purpose of this method is to save/submit the project to supply chain department.*/
    public static void  submitProjectToSHE(Project__c prjToUpsert){
        prjToUpsert.Approval_Status__c = 'Submitted';
        prjToUpsert.Department__c = 'SHE';
		upsert prjToUpsert;         
     }
    
    //Description:- Purpose of this method is to insert sharing record. 
    public static void insertSharedRecord(Product__share shareProduct){
         Database.SaveResult sr = Database.insert(shareProduct,false);
    }
}